### ISSUE TITLE
Strange DV L1 plot

### ISSUE THREAD

**Issue by 0xgrm** [nekno/DV7toDV8#4]
Hello,

I am testing your script to convert some MKV with DV profile 7 to profile 8.1.

For some files, I have strange plots like this one where it seems to only reach 100 nits. Is it a normal situation?

![Beau Is Afraid 2023 MULTi VFi 4K UHD BluRay REMUX DV HDR HEVC DTS-HD MA 5 1-Psaro DV8 L1_plot](https://github.com/nekno/DV7toDV8/assets/4482109/f75454ab-efcb-4686-b430-547e344c44f2)

**Comment by AntlerDM** [comment]
Same. This was only one of about 20 or so.

![Spectre_t01 DV8 L1_plot](https://github.com/nekno/DV7toDV8/assets/29990136/8f3b49a7-12ee-4a6c-8103-999aa837ad55)

**Comment by nekno** [comment]
For some reason, that is the way some studios have chosen to release their content, so it's effectively just HDR10 but triggers the Dolby Vision mode on the display. 

The app is calling `dovi_tool` to extract the RPU data and removing some DV7-specific and CMv4-specific L8 metadata, but isn't producing or modifying the CMv2.9 data you see plotted on the graph.

If what's left in the CMv2.9 L2 data are the trims you see graphed in the plot, then that's what's in the original RPU data.
