### ISSUE TITLE
Dolby Vision not triggered on Infuse

### ISSUE THREAD

**Issue by MelvinSDRS** [nekno/DV7toDV8#7]
I've used your script on a lot of files and it basically always worked instead for one of them. I've done it twice to be sure and it doesn't have any TrueHD track, I also tried without the FLAC audio track. You can check the plot below and the nfo before and after. Honestly I have no idea where it can come from.

![La La Land 2016 4K HDR DV 2160p BDRemux Ita Eng x265-NAHOM DV8 L1_plot](https://github.com/nekno/DV7toDV8/assets/40968328/4ad98997-d545-4577-88cd-159fffb3bdd7)

[Before converting.txt](https://github.com/nekno/DV7toDV8/files/13891516/Before.converting.txt)

[After converting.txt](https://github.com/nekno/DV7toDV8/files/13891517/After.converting.txt)

**Comment by nekno** [comment]
That's a strange one, but not completely unheard of. We really don't know _all_ the conditions required to trigger DV, so there's something in your file where we haven't yet discovered what's missing.

I think you tried everything I would've suggested based on active discussions, so I'll keep an eye on any new options that emerge that might help, but don't think there's anything to do for now. Some files just don't work. Maybe native playback on tvOS 17 will solve it when available.

**Comment by MelvinSDRS** [comment]
Yes definitively, I'm really looking forward the native DV8 playback on Infuse, I hope this will "fix" this file. Thanks for your confirmation!
